server:
  port: 1111

spring:
  application:
    name: laodoufang-taohuayuan
  datasource:
    # 数据库连接地址
    url: jdbc:mysql://106.14.210.31:3306/taohuayuan?useUnicode=true&characterEncoding=utf-8
    username: taohuayuan
    password: Taohuayuan@520
#  redis:
#    #cluster:
#      #nodes:
#        #- 127.0.0.1:6379
#    database: 0
#    host: 106.14.210.31
#    port: 6379
#    timeout: 5000
#    pool:
#      max-idle: 10
#      min-idle: 0
#      max-active: 8
#      max-wait: 1000
  data:
    mongodb:
      uri: mongodb://test:Zhangliang520@106.14.210.31:27017/test
  thymeleaf:
      mode: LEGACYHTML5
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8

mybatis:
    typeAliasesPackage: com.jamedow.laodoufang
    mapperLocations: classpath:/mapper/*.xml
    configLocation: classpath:/mybatis-config.xml



