spring:
  datasource:
    url: jdbc:mysql://106.14.210.31:3306/laodoufang?useUnicode=true&amp;characterEncoding=utf-8
    username: jamedow
    password: Zhangliang@520
  # REDIS (RedisProperties)
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 106.14.210.31
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: Z1213l520Yt
    # 连接超时时间（毫秒）
    timeout: 0
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
mybatis:
    typeAliasesPackage: com.jamedow.crawlerler
    mapperLocations: classpath:/mapper/*.xml
    configLocation: classpath:/mybatis-config.xml