server:
  port: 3333

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/

spring:
  application:
    name: laodoufang-web
  thymeleaf:
      mode: LEGACYHTML5
      cache: false
      prefix: classpath:/templates
      suffix: .html
      encoding: UTF-8



