##服务启动时，使用随机端口
server:
  port: 5555

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
          defaultZone: http://127.0.0.1:9999/eureka/

spring:
  application:
    name: laodoufang-mq
