logging:
  level:
    root: info
    com.ajavac: debug
  file: spring.log
ftp:
  port: 21
  passive-ports:
  max-login: 100
  max-threads: 100
  username: jamedow
  password: Zhangliang@520
  home-dir: laodoufang/