logging:
  level:
    root: info
    com.jamedow.laodoufang: info
#  file: spring.log
##服务启动时，使用随机端口
server:
  port: 5555

spring:
  application:
    name: laodoufang-static
  datasource:
    # 数据库连接地址
    url: jdbc:mysql://106.14.210.31:3306/laodoufang?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Zhangliang@520
#  redis:
#    #cluster:
#      #nodes:
#        #- 127.0.0.1:6379
#    database: 0
#    host: 106.14.210.31
#    port: 6379
#    timeout: 5000
#    pool:
#      max-idle: 10
#      min-idle: 0
#      max-active: 8
#      max-wait: 1000
  thymeleaf:
      mode: LEGACYHTML5
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
    typeAliasesPackage: com.jamedow.laodoufang
    mapperLocations: classpath:/mapper/*.xml
    configLocation: classpath:/mybatis-config.xml

oss:
  endpoint: oss-cn-shanghai.aliyuncs.com
  accessKeyId: LTAIuJEQ======SWXcQgOZ
  accessKeySecret: hscS01ryn5Ykk5=============7NmXyfEBVMif0gFr
  bucketName: laodoufang
  localFilePath: laodoufang
  imgServer: http://image.kxgrp.com
