logging:
  level:
    root: info
    com.jamedow.laodoufang: debug
#  file: spring.log
##服务启动时，使用随机端口
server:
  port: 5555

spring:
  application:
    name: laodoufang-static
  datasource:
    # 数据库连接地址
    url: jdbc:mysql://106.14.210.31:3306/laodoufang?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Zhangliang@520
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
      enabled: true
      resolve-lazily: false
      location: upload/userfiles

mybatis:
    typeAliasesPackage: com.jamedow.laodoufang
    mapperLocations: classpath:/mapper/*.xml
    configLocation: classpath:/mybatis-config.xml

oss:
  endpoint: oss-cn-shanghai.aliyuncs.com
  accessKeyId: LTAIuJEQSWXcQgOZ
  accessKeySecret: hscS01ryn5Ykk57NmXyfEBVMif0gFr
  bucketName: laodoufang
  localFilePath: laodoufang
  imgServer: image.laodou.site
